### ISSUE TITLE
Tutorial for the My Thai Star application

### ISSUE THREAD

**Issue by GuentherJulian** [devonfw-tutorials/tutorials#28]
Create a new tutorial for the My Thai Star sample application (https://github.com/devonfw/my-thai-star).

Possible steps:
- Download My Thai Star repository
- Run `docker-compose up` within the My Thai Star directory

**Comment by EduardKrieger** [comment]
Closing the issue, my-thai-star takes too long to start, not suitable for a katacoda tutorial.
