### ISSUE TITLE
Tutorial for devon4j application generation

### ISSUE THREAD

**Issue by GuentherJulian** [devonfw-tutorials/tutorials#32]
Create a new tutorial which describes the generation of a devon4j application.
https://github.com/devonfw/devon4j/blob/master/documentation/tutorial-newapp.asciidoc

Possible steps:
- Install the devonfw ide (you can use the `restoreDevonfwIde` command, since the installation process is not supposed to be part of this tutorial)
- Create a devon4j project
- Explain the important parts of the code
- Build the java project
- Run the application

**Comment by mustafaokyay** [comment]
Already done (PR #32)
