### ISSUE TITLE
Tutorial for devon4ng architecture

### ISSUE THREAD

**Issue by GuentherJulian** [devonfw-tutorials/tutorials#39]
Create a new tutorial which describes the devon4ng architecture.
https://devonfw.com/website/pages/docs/master-devon4ng.asciidoc_architecture.html#architecture.asciidoc
https://devonfw.com/website/pages/docs/master-devon4ng.asciidoc_layers.html

**Comment by mustafaokyay** [comment]
Tutorial already existing
