### ISSUE TITLE
devon4j migrate

### ISSUE THREAD

**Issue by maybeec** [devonfw-tutorials/tutorials#92]
We need to provide a small tutorial focusing on teaching devon4j automatic migration using java migrate
https://devonfw.com/website/pages/docs/devonfw-ide-usage.asciidoc.html#java.asciidoc

**Comment by ssarmokadam** [comment]
https://github.com/devonfw-tutorials/tutorials/pull/161

**Comment by mustafaokyay** [comment]
Already done #161
